- name: Upgrade installed packages
  package: name=* state=latest

- name: Install basic packages
  package: name={{ item }} state=present
  with_items:
      - bash-completion
      - fedora-easy-karma
      - htop
      - screen
      - tmux
      - tree
      - vim-enhanced

