# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

      config.vm.synced_folder ".", "/vagrant", disabled: true

      config.vm.provider "libvirt" do |vm|
         vm.memory = "1024"
      end
end
