- name: Add F27 libvirt box
  command: vagrant box add fedora/27-cloud-base --provider libvirt --force
  # become: no
  register: check_if_added
  until: not check_if_added | failed

- name: Find img file for Fedora box
  find:
    paths: ~/.vagrant.d/boxes/fedora-VAGRANTSLASH-27-cloud-base
    recurse: yes
    patterns: 'box.img'
  register: results
  become_user: "{{ ansible_user }}"

- assert:
    that: results['matched'] == 1
    msg: "More than one .img files were found for Fedora box"

- name: Set img file path
  set_fact:
    img_path: "{{ results['files'][0]['path'] }}"

- name: Add F27 virtualbox
  command: vagrant box add fedora/27-cloud-base --provider virtualbox --force
  # become: no
  register: check_if_added
  until: not check_if_added | failed

- debug:
    var: ansible_user_dir

- name: Find ovf file for Fedora box
  find:
    paths: ~/.vagrant.d/boxes/fedora-VAGRANTSLASH-27-cloud-base
    recurse: yes
    patterns: 'box.ovf'
  register: results
  become_user: "{{ ansible_user }}"

- assert:
    that: results['matched'] == 1
    msg: "More than one .ovf files were found for Fedora box"

- name: Set ovf file path
  set_fact:
    ovf_path: "{{ results['files'][0]['path'] }}"

- name: Get user's home directory
  getent:
    database: passwd
    key: '{{ ansible_user }}'
    split: ':'

- name: Set variable referencing user's home directory
  set_fact:
    ansible_user_home: "{{ getent_passwd[ansible_user][4] }}"

- name: Clone scenarios onto build box
  git:
    repo: git@github.com:bmbouter/SELinuxGame.git
    dest: "/var/lib/selinuxgame/SELinuxGame"
    update: yes
    key_file: "/root/.ssh/id_rsa_selinuxgame"
    version: "master"

- name: Build image
  command: packer build -var 'version'={{ version }} -var 'vagrant_cloud_token'={{ vagrant_cloud_token }} -var 'img_path'={{ img_path }} -var 'ovf_path'={{ ovf_path }} -var 'scenario_name'={{ scenario_name }} -force -parallel=false /var/lib/selinuxgame/SELinuxGame/packer_templates/selinux_scenario.json
  async: 0
  poll: 0